apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "patroni.fullname" . }}-pdb
spec:
  minAvailable: {{ sub .Values.replicaCount 1 }}
  selector:
    matchLabels:
      statefulset: {{ template "patroni.fullname" . }}
      release: {{ .Release.Name }}
