apiVersion: v1
kind: Secret
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    sts: {{ template "patroni.fullname" . }}
    cluster-name: {{ .Values.clusterName | quote }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username-superuser: {{ .Values.credentials.superuser | b64enc }}
  password-superuser: {{ default (randAlphaNum 10) .Values.somePassword | b64enc | quote }}
  username-replication: {{ .Values.credentials.replication | b64enc }}
  password-replication: {{ default (randAlphaNum 10) .Values.somePassword | b64enc | quote }}
  username-admin: {{ .Values.credentials.admin | b64enc }}
  password-admin: {{ default (randAlphaNum 10) .Values.somePassword | b64enc | quote }}
  default-dbname: {{ .Values.credentials.dbname | b64enc }}