apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vdi-project-api.fullname" . }}
  labels:
    {{- include "vdi-project-api.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "vdi-project-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "vdi-project-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vdi-project-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: audit-vol
        persistentVolumeClaim:
          claimName: {{ template "vdi-project-api.fullname" . }}-audit-pvc
      {{ if .Values.projectapi.selfSignedTLS }}
      - name: ca-bundle
        secret:
          secretName: vdi-tls
          items:
          - key: ca
            path: ca.pem
      {{ end }}
      - name: cacerts-pfx
        configMap:
          name: cacerts-pfx
      containers:
        - name: {{ .Chart.Name }}-static
          image: nginx
          ports:
            - name: lhttp
              containerPort: 80
              protocol: TCP          
          volumeMounts:
            - name: cacerts-pfx
              mountPath: /usr/share/nginx/html
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{ if .Values.projectapi.selfSignedTLS }}
          - name: REQUESTS_CA_BUNDLE
            value: "/etc/certificates/ca.pem"
          {{ end }}
          - name: HTTP_X_FORWARDED_PROTO
            value: "https"
          - name: LOG_LEVEL
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: LOG_LEVEL
          - name: API_TOKEN
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: API_TOKEN
          - name: SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: SESSION_TOKEN
          - name: VAULT_ADDR
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: VAULT_ADDR
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: VAULT_TOKEN
          - name: MINIO_ADDR
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: MINIO_ADDR
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: MINIO_SECRET_KEY
          - name: KEYCLOAK_URL
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: KEYCLOAK_URL
          - name: KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: KEYCLOAK_REALM
          - name: OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: OAUTH_CLIENT_ID
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: OAUTH_CLIENT_SECRET
          - name: KEYCLOAK_USERNAME
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: KEYCLOAK_USERNAME
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: KEYCLOAK_PASSWORD
          - name: ADMIN_GROUP
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: ADMIN_GROUP
          - name: GROUP_EXCLUSIONS
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: GROUP_EXCLUSIONS
          - name: NOTIFY_ENABLED
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: NOTIFY_ENABLED
          - name: NOTIFY_URL
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: NOTIFY_URL
          - name: NOTIFY_TOKEN
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: NOTIFY_TOKEN
          - name: SMTP_SERVER
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: SMTP_SERVER
          - name: SMTP_FROM
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: SMTP_FROM
          - name: REQUESTS_NOTIFY_EMAIL
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: REQUESTS_NOTIFY_EMAIL
          - name: KEYCLOAK_INTERNAL_URL
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: KEYCLOAK_INTERNAL_URL
          - name: KEYCLOAK_INTERNAL_REALM
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: KEYCLOAK_INTERNAL_REALM
          - name: KEYCLOAK_INTERNAL_USERNAME
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: KEYCLOAK_INTERNAL_USERNAME
          - name: KEYCLOAK_INTERNAL_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: KEYCLOAK_INTERNAL_PASSWORD
          - name: HUB_REDIRECT_URL
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: HUB_REDIRECT_URL
          - name: RECORDER_URL
            valueFrom:
              secretKeyRef:
                  name: vdi-project-api-secret
                  key: RECORDER_URL
          volumeMounts:
          - name: audit-vol
            mountPath: /audit
          {{ if .Values.projectapi.selfSignedTLS }}
          - name: ca-bundle
            mountPath: /etc/certificates
          {{ end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/projects/status
              port: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
