apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "vdi-project-api.fullname" . }}-audit-pvc
  {{- with .Values.storageAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{ end }}
  labels:
      app: {{ template "vdi-project-api.name" . }}-vdi-project-api
      chart: {{ template "vdi-project-api.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.size}}
{{ if .Values.storage.className }}
  storageClassName: {{.Values.storage.className}}
{{ end }}
