{{- if .Values.ingress.enabled -}}
## FUTURE: When k8s 1.20 is released or when we can assume k8s 1.14, switch from
##         apiVersion: extensions/v1beta1 to using apiVersion:
##         networking.k8s.io/v1beta1.
##
## ref: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
##
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $.Values.hub.baseUrl }}{{ $.Values.ingress.pathSuffix }}
            backend:
              serviceName: proxy-public
              servicePort: 80
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}
