---
apiVersion: v1
kind: Service
metadata:
    name: {{ template "apache-nifi.fullname" . }}-headless
    labels:
        app: {{ include "apache-nifi.name" . | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
    type: {{ .Values.service.headless.type }}
    clusterIP: None
    ports:
{{- if .Values.properties.clusterSecure }}
    - port: {{ .Values.properties.httpsPort }}
      name: https
{{- else}}
    - port: {{ .Values.properties.httpPort }}
      name: http
{{- end }}
    - port: {{ .Values.properties.clusterPort }}
      name: cluster
    selector:
        app: {{ include "apache-nifi.name" . | quote }}
        release: {{ .Release.Name | quote }}
---
{{- if .Values.service.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.service.loadBalancer.annotations }}
  annotations:
{{ toYaml .Values.service.loadBalancer.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.loadBalancer.type }}
  {{- if .Values.service.loadBalancer.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancer.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancer.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ with .Values.service.loadBalancerSourceRanges }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- end }}
  ports:
{{- if .Values.properties.clusterSecure }}
    - port: {{ .Values.service.loadBalancer.httpsPort }}
      name: https
    {{- if and (eq "NodePort" .Values.service.loadBalancer.type) .Values.service.loadBalancer.nodePort }}
      nodePort: {{ .Values.service.loadBalancer.nodePort }}
    {{- end }}
      targetPort: {{ .Values.properties.httpsPort }}
{{- else }}
    - port: {{ .Values.service.loadBalancer.httpPort }}
      name: http
      targetPort: {{ .Values.properties.httpPort }}
{{- end }}
  selector:
    app: {{ template "apache-nifi.name" . }}
    release: {{ .Release.Name }}
{{- end }}
