# Default values for ocp-terraform-pipelines
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  create: false
  rules: []
  # RBAC rules
  #  - apiGroups:
  #      - ""
  #    resources:
  #      - pods
  #    verbs:
  #      - get
  #      - list

webhookKey: ""

releaseNamespace: mc

# Github package containing the terraform configuration to pull
packageRef: "@bcgov-dss/api-serv-infra"
#packageTag: "dev"
# 'dev' or blank

# Set the releaseBranch to the branch in api-serv-infra that holds the 'version' file
# The 
deployRepo: https://github.com/bcgov-dss/api-serv-infra.git
deployBranch: deploy/dev

# Access token with "read:packages" scope in Github
githubAccessToken: ""

# Terraform Postgresql backend for managing state
terraformFolder: terraform/workspaces/dev
terraformBackendPostgresql: "conn_str=postgres://[USER]:[PSWD]@[HOST]/[DATABASE]?sslmode=disable"

terraformVersion: "0.12.29"

# The following tfvars gets converted to a file 'terraform.secret.auto.tfvars', used during terraform apply
tfvars: {}
