{{- if .Values.oauthProxy.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-api.fullname" . }}-proxy-config
  labels:
    app: {{ include "generic-api.name" . }}
    chart: {{ include "generic-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range .Values.oauthProxy.config }}
  {{ .filename }}: |-
{{- with .contents }}
{{ . | indent 4 }}
{{- end }}
{{- with .yaml }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
