{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "generic-api.fullname" . }}-pdb
  labels:
    app: {{ include "generic-api.name" . }}
    release: {{ .Release.Name }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "generic-api.name" . }}
      release: {{ .Release.Name }}
{{- end }}