{{- range $name, $val := .Values.persistence }}
{{- if (and (not .claimName) (.persistentVolumeClaim)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "generic-api.fullname" $ }}-{{ $name }}-pvc
  {{- with $.Values.storageAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{ end }}
  labels:
      app: {{ template "generic-api.name" $ }}
      chart: {{ template "generic-api.chart" $ }}
      release: {{ $.Release.Name }}
      heritage: {{ $.Release.Service }}
spec:
  accessModes:
    - {{.storageAccessMode}}
  storageClassName: {{.storageClassName}}
  resources:
    requests:
      storage: {{.size}}
---
{{- end }}
{{- end }}
