{{- if and .Values.rbac.create .Values.rbac.rules }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "generic-api.fullname" . }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "generic-api.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "generic-api.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.podServiceAccountName | default (printf "%s" (include "generic-api.serviceAccountName" . )) }}
    namespace: {{ .Release.Namespace }}
{{- end }}
