apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-api.fullname" . }}-secrets
  labels:
    app: {{ include "generic-api.name" . }}
    chart: {{ include "generic-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $index, $val := .Values.env }}
  {{- if .secure }}
  {{ $index | kebabcase }}: {{ .value | b64enc | quote }}
  {{ end }}
{{ end }}
