apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-api.fullname" . }}
  labels:
    {{- include "generic-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.oauthProxy.enabled }}
      targetPort: proxy
      {{- else }}
      targetPort: http
      {{- end }}
      protocol: TCP
      name: http
  {{- range .Values.extraPorts }}
    - port:  {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "generic-api.selectorLabels" . | nindent 4 }}
