{{- if .Values.events.install -}}

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Release.Name }}-tek-github-secret
#   labels:
#     app: {{ template "pipelines.name" $ }}
#     chart: {{ template "pipelines.chart" $ }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
# type: Opaque
# stringData:
#   secretToken: {{ .Values.events.token }}

{{- if .Values.events.defaultRB -}}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: defaultEdit
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
{{- end -}}


{{ range .Values.events.listeners }}

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .name }}
  labels:
    app: {{ template "pipelines.name" $ }}
    chart: {{ template "pipelines.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
  triggers:
    {{- range .triggers }}
    - template:
        name: {{ .trigger }}
      bindings:
        - name: {{ .binding }}
          value: {{ .binding }}
      # interceptors:
      #   - ref:
      #       name: "github"
      #     params:
      #       - name: "secretRef"
      #         value:
      #           secretName: {{ $.Release.Name }}-tek-github-secret
      #           secretKey: secretToken
    {{- end -}}

{{- end -}}
{{ end }}