
{{ range .Values.services }}

{{ if .env }}
{{ if gt (len .env) 0 }}
{{ range .env }}
{{ if .secret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    app: {{ template "pipelines.name" $ }}
    chart: {{ template "pipelines.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: Opaque
stringData:
  {{ .secretKey }}: {{ .secretValue }}

---

{{ end }}
{{ end }}
{{ end }}
{{ end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ template "pipelines.name" $ }}-{{ .name }}
    chart: {{ template "pipelines.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "pipelines.name" $ }}-{{ .name }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pipelines.name" $ }}-{{ .name }}
        release: {{ $.Release.Name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{ if .env }}
          {{ if gt (len .env) 0 }}
          env:
            {{ range .env }}
            {{ if .secret }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .secretName }}"
                  key: "{{ .secretKey }}"
            {{ else }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{ end }}
            {{ end }}
          {{ end }}
          {{ end }}
          ports:
            - name: http
              containerPort: {{ .port }}
          resources:
{{ toYaml .resources | indent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ template "pipelines.name" $ }}
    chart: {{ template "pipelines.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "pipelines.name" $ }}-{{ .name }}
    release: {{ $.Release.Name }}

---

{{- end -}}