

{{- if .Values.events.install -}}
{{range .Values.events.listeners}}
{{- if .ingress.enabled -}}
{{ $ingressPath := .ingress.path }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .ingress.name }}
  labels:
    app: {{ template "pipelines.name" $ }}
    chart: {{ template "pipelines.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- with .ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .ingress.tls }}
  tls:
  {{- range .ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{ range $i, $host := .ingress.hosts }}
    - host: {{ $host.name }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $host.service }}
              servicePort: {{ $host.port }}
  {{- end }}
{{ end }}
{{- end -}}
{{- end -}}