{{- if and (.Values.tls.enabled) (eq .Values.tls.secretName "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-api.fullname" . }}-tls
  labels:
    app: {{ include "generic-api.name" . }}
    chart: {{ include "generic-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  server.key: |
{{ index .Values.tls.secret "server.key" | b64enc | indent 4 }}
  server.crt: |
{{ index .Values.tls.secret "server.crt" | b64enc | indent 4 }}
  ca.crt: |
{{ index .Values.tls.secret "ca.crt" | b64enc | indent 4 }}
{{ end }}