{{ if .Values.notifications.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ include "ocp-tkn-terraform-pipeline.fullname" . }}-teams-notif
  labels:
    {{- include "ocp-tkn-terraform-pipeline.labels" . | nindent 4 }}
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: messaging
    tekton.dev/displayName: "Send message to Microsoft Teams Channel"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    These tasks post a simple message to a Microsoft Teams Channel.
    This task uses the Incoming Webhook functionality of Microsoft Teams
  params:
    - name: webhookUrlSecret
      type: string
      description: Name of the secret with incoming webhook URL
      default: {{ include "ocp-tkn-terraform-pipeline.fullname" . }}-teams-whk
    - name: webhookUrlSecretKey
      type: string
      description: Key in the secret
      default: webhook-url
    - name: pipelineRunName
      type: string
      description: The name of the pipeline run
  steps:
    - name: post
      image: docker.io/curlimages/curl:7.70.0@sha256:031df77a11e5edded840bc761a845eab6e3c2edee22669fb8ad6d59484b6a1c4 #tag: 7.70.0
      script: |
        #!/usr/bin/env sh
        MESSAGE=$(echo "${MESSAGE}" | sed -e 's/\"/\\\\"/g')
        JSON="{\"text\": \"${MESSAGE}\" }"
        curl -X POST -H 'Content-Type: application/json' -d "${JSON}" "${WEBHOOK_URL}"
      env:
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: $(params.webhookUrlSecret)
              key: $(params.webhookUrlSecretKey)
        - name: MESSAGE
          value: Deployment $(params.pipelineRunName) Failed!
{{ end }}