apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocp-tkn-terraform-pipeline.fullname" . }}-git-webhook
  labels:
    {{- include "ocp-tkn-terraform-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  secretToken: {{ .Values.githubWebhookSecret | b64enc }}
