apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "batch-job.fullname" . }}-config
  labels:
    app: {{ include "batch-job.name" . }}
    chart: {{ include "batch-job.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ range .Values.configEnv }}
  {{ .name | kebabcase }}: {{ .value | quote }}
{{ end }}
