apiVersion: v2
name: metadata-curator
description: A Helm chart for Metadata Curator
author: Brandon Sharratt

type: application


version: 0.1.14

appVersion: 0.9.0

dependencies:
    - name: forum-api
      version: 0.1.0
      repository: https://bcgov.github.io/helm-charts/
  
    - name: formio
      version: 0.1.0
      repository: https://bcgov.github.io/helm-charts/
  
    - name: storage-api
      version: 0.1.3
      repository: https://bcgov.github.io/helm-charts/
  