apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ include "ocp-tkn-terraform.fullname" . }}-cleanup
  labels:
    {{- include "ocp-tkn-terraform.labels" . | nindent 4 }}
spec:
  description: >-
    This task runs commands against the cluster provided by user
    and if not provided then where the Task is being executed.
    OpenShift is a Kubernetes distribution from Red Hat which provides oc,
    the OpenShift CLI that complements kubectl for simplifying deployment
    and configuration applications on OpenShift.
  params:
    - name: ocCliVersion
      description: The OpenShift Version to use
      type: string
      default: "4.7"
    - name: retainDays
      description: Pipelineruns are only kept up to this number of days
      type: string
      default: "5"
  steps:
    - env:
        - name: RETAIN_DAYS
          value: $(params.retainDays)
      name: oc
      image: quay.io/openshift/origin-cli:$(params.ocCliVersion)
      script: |
        #!/usr/bin/env bash
        
        set -x

        [[ "$(workspaces.cleanup.bound)" == "true" ]] && \
        cd $(workspaces.cleanup.path)

        oc get pipelineruns -l "tekton.dev/pipeline={{ include "ocp-tkn-terraform.fullname" . }}" -o go-template --template {{`'{{range .items}}{{.metadata.name}} {{.metadata.creationTimestamp}}{{"\n"}}{{end}}'`}} | awk '$2 <= "'$(date -d "now-${RETAIN_DAYS} days" -Ins --utc | sed 's/+0000/Z/')'" { print $1 }' | xargs --no-run-if-empty oc delete pipelineruns

  workspaces:
    - name: cleanup
