apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocp-tkn-terraform.fullname" . }}-git-auth
  labels:
    {{- include "ocp-tkn-terraform.labels" . | nindent 4 }}
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.githubAccessToken | b64enc }}
  password: ""