{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}-git-clone
  labels:
    {{- include "ocp-tkn-terraform.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ include "ocp-tkn-terraform.fullname" . }}-git-auth
{{- end }}
