apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "konga.fullname" . }}-node-seed
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kong_node.data: |
    module.exports = [
        {
            "name": "Kong",
            "type": "key_auth",
            "kong_admin_url": "http://kong:8001",
            "kong_api_key": "DonKeyKong",
            "health_checks": false,
        }
    ]
  