apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vdi-project-api.fullname" . }}-secret
type: Opaque
data:
  LOG_LEVEL: "{{ .Values.projectapi.logLevel | b64enc }}"
  API_TOKEN: "{{ .Values.projectapi.apiToken | b64enc }}"
  SESSION_TOKEN: "{{ .Values.projectapi.sessionToken | b64enc }}"

  VAULT_ADDR: "{{ .Values.projectapi.vault.addr | b64enc }}"
  VAULT_TOKEN: "{{ .Values.projectapi.vault.token | b64enc }}"

  MINIO_ADDR: "{{ .Values.projectapi.minio.addr | b64enc }}"
  MINIO_ACCESS_KEY: "{{ .Values.projectapi.minio.accessKey | b64enc }}"
  MINIO_SECRET_KEY: "{{ .Values.projectapi.minio.secretKey | b64enc }}"

  KEYCLOAK_URL: "{{ .Values.projectapi.keycloak.url | b64enc }}"
  KEYCLOAK_REALM: "{{ .Values.projectapi.keycloak.realm | b64enc }}"
  KEYCLOAK_USERNAME: "{{ .Values.projectapi.keycloak.username | b64enc }}"
  KEYCLOAK_PASSWORD: "{{ .Values.projectapi.keycloak.password | b64enc }}"

  OAUTH_CLIENT_ID: "{{ .Values.projectapi.selfserve.clientId | b64enc }}"
  OAUTH_CLIENT_SECRET: "{{ .Values.projectapi.selfserve.clientSecret | b64enc }}"

  ADMIN_GROUP: "{{ .Values.projectapi.adminGroup | b64enc }}"

  GROUP_EXCLUSIONS: "{{ .Values.projectapi.groupExclusions | b64enc }}"

  NOTIFY_ENABLED: "{{ .Values.projectapi.webhook.enabled | b64enc }}"
  NOTIFY_URL: "{{ .Values.projectapi.webhook.url | b64enc }}"
  NOTIFY_TOKEN: "{{ .Values.projectapi.webhook.token | b64enc }}"

  SMTP_SERVER: "{{ .Values.projectapi.smtp.server | b64enc }}"
  SMTP_FROM: "{{ .Values.projectapi.smtp.from | b64enc }}"

  REQUESTS_NOTIFY_EMAIL: "{{ .Values.projectapi.applications.approvalEmail | b64enc }}"

  KEYCLOAK_INTERNAL_URL: "{{ .Values.projectapi.keycloakInternal.url | b64enc }}"
  KEYCLOAK_INTERNAL_REALM: "{{ .Values.projectapi.keycloakInternal.realm | b64enc }}"
  KEYCLOAK_INTERNAL_USERNAME: "{{ .Values.projectapi.keycloakInternal.username | b64enc }}"
  KEYCLOAK_INTERNAL_PASSWORD: "{{ .Values.projectapi.keycloakInternal.password | b64enc }}"

  HUB_REDIRECT_URL: "{{ .Values.projectapi.hubRedirectUrl | b64enc }}"

  RECORDER_URL: "{{ .Values.projectapi.recorderUrl | b64enc }}"
