apiVersion: v1
kind: Service
metadata:
  name: {{ include "vdi-project-api.fullname" . }}
  labels:
    {{- include "vdi-project-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vdi-project-api.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vdi-project-api.fullname" . }}-static
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: lhttp
      protocol: TCP
      name: lhttp
  selector:
    {{- include "vdi-project-api.selectorLabels" . | nindent 4 }}
