{{ range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
type: Opaque
data:
    {{- if .toJSon }}
    config: '{{ .value | toJson | b64enc }}'
    {{ else }}
    config: '{{ .value | b64enc }}'
    {{ end }}
    
{{ end -}}
