apiVersion: v1
name: patroni
description: 'Highly available elephant herd: HA PostgreSQL cluster.'
version: 0.21.0
appVersion: 1.6-p3
home: https://github.com/zalando/patroni
sources:
- https://github.com/zalando/patroni
- https://github.com/zalando/spilo
maintainers:
- name: Matthieu Foucault
  email: matthieu@button.is
