serviceAccountName: build-bot

nameOverride: ""
fullnameOverride: ""

repos:
  - name: ds-infra-git
    branch: master
    url: git@github.com:bcgov-idd/ds-infra.git

tasks:
  - name: helm3-spark
    resources:
      - name: ds-infra-git
        type: git
    steps:
      - name: install-spark
        image: alpine/helm:3.0.2
        command:
          - /bin/ash
          - "-c"
          - "helm repo add stable https://kubernetes-charts.storage.googleapis.com/ && helm upgrade --install -n spark spark stable/spark"

pipelines:
  - name: spark-pipeline
    namespace: pipelines
    createNamespace: spark
    triggerName: spark-trigger-template
    bindingName: spark-binding
    tasks:
      - name: create-namespace-spark
        ref: 
          name: create-namespace-spark
      - name: helm3-spark
        ref: 
          name: helm3-spark


events:
  install: true
  token: "token"
  listeners:
    - name: ds-infra-listener
      triggers:
        - trigger: spark-trigger-template
          binding: spark-binding
      ingress:
        enabled: true
        name: spark-pipeline-ingress
        annotations:
          kubernetes.io/ingress.class: nginx
        path: /
        hosts:
          - name: chart-example.local
            service: webhook-service
            port: 3000
        tls: []