
{{- if .Values.gpg.private_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apache-nifi.fullname" . }}-gpg
  labels:
    app: {{ template "apache-nifi.name" . }}
    chart: {{ template "apache-nifi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  gpgPrivateKey: {{ .Values.gpg.private_key }}
  gpgPassphrase: {{ .Values.gpg.passphrase | b64enc }}
{{ end }}