{{- $HTTPS := (and .Values.proxy.https.hosts .Values.proxy.https.enabled) }}
{{- $autoHTTPS := (and $HTTPS (eq .Values.proxy.https.type "letsencrypt")) }}
{{- if $autoHTTPS -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-proxy-config
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  proxy-body-size: "{{ .Values.proxy.nginx.proxyBodySize }}"
  hsts-include-subdomains: "{{ .Values.proxy.nginx.hstsIncludeSubdomains }}"
{{- end }}
