apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aps-gateway-ns.fullname" . }}-config
  labels:
    app: {{ include "aps-gateway-ns.name" . }}
    chart: {{ include "aps-gateway-ns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  gateway.yaml: |-
    services:
{{- range $suffix, $config := .Values.services }}
{{ toYaml $config | indent 4 }}
{{- end }}

{{- range .Values.config }}
  {{ .filename }}: |-
{{- with .contents }}
{{ . | indent 4 }}
{{- end }}
{{- with .yaml }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aps-gateway-ns.fullname" . }}-scripts
  labels:
    app: {{ include "aps-gateway-ns.name" . }}
    chart: {{ include "aps-gateway-ns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}
