{{- if and .Values.rbac.create .Values.rbac.rules }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aps-gateway-ns.fullname" . }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aps-gateway-ns.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aps-gateway-ns.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aps-gateway-ns.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
