apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aps-gateway-ns.fullname" . }}-secrets
  labels:
    app: {{ include "aps-gateway-ns.name" . }}
    chart: {{ include "aps-gateway-ns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $index, $val := .Values.env }}
  {{- if .secure }}
  {{ $index | kebabcase }}: {{ .value | b64enc | quote }}
  {{ end }}
{{ end }}

stringData:
{{- with .Values.directoryConfig }}
{{- if .products }}
  products.yaml: |-
    products:
{{ toYaml .products | indent 4 }}
{{- end }}
{{- if .datasets }}
  datasets.yaml: |-
    datasets:
{{ toYaml .datasets | indent 4 }}
{{- end }}
{{- if .issuers }}
  issuers.yaml: |-
    issuers:
{{ toYaml .issuers | indent 4 }}
{{- end }}
{{- end }}