apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aps-gateway-ns.fullname" . }}-secrets
  labels:
    app: {{ include "aps-gateway-ns.name" . }}
    chart: {{ include "aps-gateway-ns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $index, $val := .Values.env }}
  {{- if .secure }}
  {{ $index | kebabcase }}: {{ .value | b64enc | quote }}
  {{- end }}
{{- end }}
