{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metadata-curator.serviceAccountName" . }}
  labels:
{{ include "metadata-curator.labels" . | nindent 4 }}
{{- end -}}
