apiVersion: v1
name: patroni
description: 'Highly available elephant herd: HA PostgreSQL cluster.'
version: 2.0.0
appVersion: 12.4-patroni-1.6.5
home: https://github.com/bcgov/patroni-postgres-container
sources:
- https://github.com/helm/charts/tree/master/incubator/patroni
- https://github.com/BCDevOps/platform-services/blob/master/apps/pgsql/patroni
maintainers:
- name: ll911
  email: leo.lou@gov.bc.ca
- name: aidan cope
  email: aidan.cope@gmail.com
