apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-serv-ui.fullname" . }}-config
  labels:
    app: {{ include "api-serv-ui.name" . }}
    chart: {{ include "api-serv-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ range .Values.configEnv }}
  {{ .name | kebabcase }}: {{ .value | quote }}
{{ end }}
  argg.caddyfile: |-
      0.0.0.0
      log stdout
      errors stderr
      proxy /api http://localhost:8000 {
        without /api
        transparent
      }
      proxy /registryapi {$BCDC_API_URL} {
        without /registryapi
      }
      root /srv