apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-serv-ui.fullname" . }}
  labels:
    {{- include "api-serv-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-proxy
      protocol: TCP
      name: http-proxy
  selector:
    {{- include "api-serv-ui.selectorLabels" . | nindent 4 }}
