nameOverride: ""
fullnameOverride: ""

tasks:


pipelines:
  - name: geocoder-clone-repo
    triggerName: geocoder-trigger-pr-open
    bindingName: geocoder-binding-pr-open
    serviceAccountName:
      - pipelineTaskName: clone-repo
        taskServiceAccountName: pipeline
    pipeline_params:
      - name: git-url
        type: string
        description: git repo url
        incomingValue: $(body.repository.ssh_url)
        resourceTemplate: $(tt.params.git-url)
      - name: git-revision
        type: string
        description: pull request head commit id
        default: main
        incomingValue: $(body.pull_request.head.sha)
        resourceTemplate: $(tt.params.git-revision)
    workspaces:
      - name: shared-workspace
        volumeClaimTemplate: 1Gi
    tasks:
      - name: clone-repo
        workspaces:
          - name: output
            workspace: shared-workspace
        ref:
          kind: ClusterTask
          name: git-clone
        params:
          - name: url
            value: https://github.com/bcgov/ols-geocoder.git
            # value: $(params.git-url)
          - name: revision
            value: $(params.git-revision)

events:
  install: true
  defaultRB: false
  listeners:
    - name: geocoder-listener-helm
      triggers:
        - name: pr-open-trigger
          trigger: geocoder-trigger-pr-open
          binding: geocoder-binding-pr-open
          interceptors:
            - name: github
              eventTypes:
                - name: pull_request
            - name: cel
              filter: "body.action in ['opened', 'reopened']"
      ingress:
        enabled: true
        name: geocoder-ingress-helm
        annotations:
          openshift.io/host.generated: 'true'
        host: el-geocoder-listener-helm-988040-tools.apps.silver.devops.gov.bc.ca
        service: el-geocoder-listener-helm
