serviceAccountName: git-bot

nameOverride: ""
fullnameOverride: ""

tasks:
  - name: maven-helm
    volumes:
    - name: m2-vol
      persistentVolumeClaim: pip-tkt-m2-pvc
    - name: conf-vol
      configMap: maven-config
    workspaces:
      - name: source
    steps:
      - name: build
        image: maven:3.8.2-jdk-11-slim
        command:
          - /bin/bash
          - "-s"
          - "/workspace/mvn-config/settings.xml"
          - "/usr/bin/mvn"
          - "install"
        env:
        - name: MAVEN_OPTS
          value: "-server -Xms256m -Xmx512m -XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90"
        volumeMounts:
        - name: conf-vol
          mountPath: /workspace/mvn-config
        - name: m2-vol
          mountPath: /workspace/.m2/repository
        workingDir: /workspace/source
        resources:
          requests:
            memory: 500Mi
            cpu: 250m
          limits:
            memory: 3Gi
            cpu: "2"


pipelines:
  - name: geomark-clone-helm
    triggerName: geomark-trigger-helm
    bindingName: geomark-binding-helm
    pipeline_params:
      - name: git-url
        type: string
        description: git repo url
        incomingValue: $(body.repository.ssh_url)
        resourceTemplate: $(tt.params.git-url)
      - name: pr-url
        description: pull request url
        type: string
        incomingValue: $(body.pull_request.html_url)
        resourceTemplate: $(tt.params.pr-url)
      - name: git-revision
        type: string
        description: pull request head commit id
        default: main
        incomingValue: $(body.pull_request.head.sha)
        resourceTemplate: $(tt.params.git-revision)
    workspaces:
      - name: output
        workspace: shared-workspace
        persistentVolumeClaim: pip-tkt-repo-pvc
    podTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
    tasks:
      - name: clone-repo
        workspaces:
          - name: output
            workspace: shared-workspace
        ref:
          kind: ClusterTask
          name: git-clone
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.git-revision)
      - name: maven-build
        ref:
          name: maven-helm
        runAfter:
          - clone-repo
        workspaces:
        - name: source
          workspace: shared-workspace

events:
  install: true
  defaultRB: true
  token: token
  listeners:
    - name: geomark-listener-helm
      triggers:
        - name: pr-open-trigger
          trigger: geomark-trigger-helm
          binding: geomark-binding-helm
          interceptors:
            - name: github
              eventTypes:
                - name: pull_request
              secretName: github-secret
            - name: cel
              filter: "body.action in ['opened', 'reopened']"
      ingress:
        enabled: true
        name: geomark-ingress-helm
        annotations:
          kubernetes.io/ingress.class: nginx
        path: /
        hosts:
          - name: el-geomark-listener-helm-f8d638-tools.apps.silver.devops.gov.bc.ca
            service: el-geomark-listener-helm
            port: 8080
        tls: []
