apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "userguide-bridge-api.fullname" . }}
  labels:
{{ include "userguide-bridge-api.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "userguide-bridge-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "userguide-bridge-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: LOG_LEVEL
            value: {{ .Values.userguide.logLevel }}
          - name: API_TOKEN
            valueFrom:
              secretKeyRef:
                  name: {{ template "userguide-bridge-api.fullname" . }}-secret
                  key: API_TOKEN
          - name: HELP_API_HOST
            value: "{{ .Values.userguide.helpApiHost }}"
          - name: HELP_API_TOKEN
            valueFrom:
              secretKeyRef:
                  name: {{ template "userguide-bridge-api.fullname" . }}-secret
                  key: HELP_API_TOKEN
          - name: HELP_APPS
            value: "{{ .Values.userguide.helpApps }}"
          - name: HELP_DOCUMENT_TYPES
            value: "{{ .Values.userguide.helpDocumentTypes }}"
          - name: CORS_WHITELIST
            value: "{{ .Values.userguide.corsWhitelist }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
