apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
    githubAccessToken: '{{ .Values.githubAccessToken | b64enc }}'
    tfvars: {{ tpl "{{ range $i, $e := .Values.tfvars }}{{$i}} = {{ if kindIs \"string\" $e }}{{ $e | toJson }}{{ else }} {\n{{ range $i2, $e2 := $e }}    {{ $i2 }} = \"{{ $e2 }}\",\n{{ end }}}{{ end }}\n{{ end }}" . | b64enc }}
