apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce.
    - name: BUILDAH_IMAGE
      description: Reference the image version of buildah.
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: vfs
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: Path to the Dockerfile to build.
      default: .
  workspaces:
    - name: source
    - name: dockerconfig
      description: Includes a docker config file named `.dockerconfigjson`
      optional: true
      mountPath: /root/.docker/
  steps:
    - name: build
      image: $(params.BUILDAH_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) bud \
          --no-cache -f $(params.DOCKERFILE) -t $(params.IMAGE) --isolation chroot $(params.CONTEXT)
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      resources:
        requests:
          memory: 2Gi
          cpu: "2"
        limits:
          memory: 4Gi
          cpu: "4"
    - name: push
      image: $(params.BUILDAH_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        # grab jq
        curl -L -O https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux32
        chmod ugo+x ./jq-linux32  

        # push with creds from dockerconfig secret
        AUTH=$(./jq-linux32 '.["image-registry.apps.silver.devops.gov.bc.ca"].auth' -r /root/.docker/.dockerconfigjson | base64 -d)
        buildah --storage-driver=$(params.STORAGE_DRIVER) push \
          --creds="$AUTH" --tls-verify=0 --authfile /root/.docker/.dockerconfigjson $(params.IMAGE)
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
      emptyDir: {}
