apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    wip: 'true'
  name: {{ include "ocp-tekton-ckan-ui.fullname" . }}
spec:
  tasks:
    - name: clone-ckan-ui-repo
      params:
        - name: url
          value: 'https://github.com/bcgov/ckan-ui.git'
        - name: revision
          value: {{ .Values.branch }}
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.21.0
        - name: subdirectory
          value: ckan-ui
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace

  workspaces:
    - name: shared-workspace
