apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    sts: {{ template "patroni.fullname" . }}
    cluster-name: {{ .Values.clusterName | quote }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    cluster-name: {{ .Values.clusterName | quote }}
    role: master
    sts: {{ template "patroni.fullname" . }}
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
