# Default values for ocp-pipelines
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

routes:
#  - host: ""
#    targetPort: service
#    service: xyz-service
#    wildcardPolicy: None
#    tls:
#      termination: edge