apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "api-serv-gwa.fullname" . }}-tc-config
  labels:
    app.kubernetes.io/name: {{ include "api-serv-gwa.name" . }}
    helm.sh/chart: {{ include "api-serv-gwa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (tpl (.Files.Glob "configs/*").AsConfig . ) | indent 2 }}
