config: |-
  # kind: GatewayService
  # name: <MYSERVICE>
  # tags: [ __NS__ ]
  # url: https://httpbin.org
  # retries: 0
  # routes:
  #   - name: <MYSERVICE>
  #     tags: [ __NS__ ]
  #     hosts: [<MYSERVICE>.api.gov.bc.ca]
  #     methods: [GET]
  #     paths: [/]

networkPolicy:
  create: true
  namespaces: []
  #ports: [ 80, 8080 ]
  matchLabels:
    {}
    # name: my-upstream-api

vault:
  use: false
  # authPath: auth/k8s-silver
  # namespace: platform-services
  # role: xxxxxx-nonprod
  # secret: xxxxxx-nonprod/api-gateway
  #
  # The secret should have the following JSON:
  # {
  #   "NAMESPACE": "",
  #   "CLIENT_ID": "",
  #   "CLIENT_SECRET": "",
  #   "GWA_HOST": ""
  # }

# If you are not using Vault, you can set the following variables
env:
  NAMESPACE:
    value: ""
    secure: true
  CLIENT_ID:
    value: ""
    secure: true
  CLIENT_SECRET:
    value: ""
    secure: true
  GWA_HOST:
    value: "api.gov.bc.ca" # test/training: api-gov-bc-ca.test.api.gov.bc.ca
    secure: true

nameOverride: ""
fullnameOverride: ""

image:
  repository: docker.io/kubeless/unzip
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

shell: sh

serviceAccount:
  create: false
  # annotations: {}
  # The name of the service account to use.
  # name: "xxxxxx-vault"

podSecurityContext: {}

securityContext: {}

extraLabels: []

podAnnotations: {}

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

job:
  backoffLimit: 0 # specify the number of retries before considering a Job as failed
  restartPolicy: Never # Never: a Job will run uninterrupted unless a Pod fails
  ttlSecondsAfterFinished: 31536000 #31536000 # Deletes the job after n seconds : 86400 = 24 hours, 31536000 = 1 year
