config: |-
  # kind: GatewayService
  # name: <MYSERVICE>
  # tags: [ __NS__ ]
  # url: https://httpbin.org
  # retries: 0
  # routes:
  #   - name: my-service-for-69cfb
  #     tags: [ __NS__ ]
  #     hosts: [<MYSERVICE>.api.gov.bc.ca]
  #     methods: [GET]
  #     paths: [/]

networkPolicy:
  create: true
  namespaces: []
  #ports: [ 80, 8080 ]
  matchLabels:
    {}
    # name: my-upstream-api

vault:
  use: false
  # authPath: auth/k8s-silver
  # namespace: platform-services
  # role: xxxxxx-nonprod
  # secret: xxxxxx-nonprod/api-gateway
  #
  # The secret should have the following JSON:
  # {
  #   "NAMESPACE": "",
  #   "CLIENT_ID": "",
  #   "CLIENT_SECRET": "",
  #   "GWA_HOST": ""
  # }

# If you are not using Vault, you can set the following variables
env:
  # {}
  NAMESPACE:
    value: "gw-69cfb"
    secure: true
  CLIENT_ID:
    value: "sa-gw-69cfb-ca853245-4605619ec2a2"
    secure: true
  CLIENT_SECRET:
    value: "55c8369b-6443-4bf8-b1ea-dd1d0f1dbd41"
    secure: true
  GWA_HOST:
    value: "api-gov-bc-ca.dev.api.gov.bc.ca"
    secure: true

nameOverride: ""
fullnameOverride: ""

image:
  repository: docker.io/kubeless/unzip
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

shell: sh

serviceAccount:
  create: false
  # annotations: {}
  # The name of the service account to use.
  # name: "xxxxxx-vault"

podSecurityContext: {}

securityContext: {}

extraLabels: []

podAnnotations: {}

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

job:
  backoffLimit: 0 # specify the number of retries before considering a Job as failed
  restartPolicy: Never # Never: a Job will run uninterrupted unless a Pod fails
  ttlSecondsAfterFinished: 86400 # Deletes the job after n seconds : 86400 = 24 hours, 31536000 = 1 year
