apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-serv-ui.fullname" . }}-secrets
  labels:
    app: {{ include "api-serv-ui.name" . }}
    chart: {{ include "api-serv-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ range .Values.secureEnv }}
  {{ .name | kebabcase }}: {{ .value | b64enc | quote }}
{{ end }}
