apiVersion: v1
kind: Secret
metadata:
  name: {{ template "userguide-bridge-api.fullname" . }}-secret
type: Opaque
data:
  API_TOKEN: {{ .Values.userguide.apiToken | b64enc }}
  HELP_API_TOKEN: {{ .Values.userguide.helpApiToken | b64enc }}
