# Default values for generic-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.18.0"

imagePullSecrets: []

args: {}

nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  fsGroup: 1010820000

securityContext:
  runAsUser: 1010820000
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true

extraLabels: []

persistence: {}
#  temp:
#    mountPath: /tmp

config:
  []
  # - filename: index.html
  #   mountPath: /usr/share/nginx/html/index.html
  #   contents: |
  #     <html><body>My web service</body></html>
  # - filename: nginx.conf
  #   mountPath: /etc/nginx/nginx.conf
  #   contents: |
  #     worker_processes  1;
  #     error_log  /tmp/error.log;
  #     pid        /tmp/nginx.pid;
  #     worker_rlimit_nofile 8192;

  #     events {
  #       worker_connections  1024;
  #     }

  #     http {
  #         client_body_temp_path /tmp/client_temp;
  #         proxy_temp_path       /tmp/proxy_temp_path;
  #         fastcgi_temp_path     /tmp/fastcgi_temp;
  #         uwsgi_temp_path       /tmp/uwsgi_temp;
  #         scgi_temp_path        /tmp/scgi_temp;

  #         server {
  #           listen       8000;
  #           root         /usr/share/nginx/html;
  #         }
  #     }

env:
  {}
  # SOME_ENV_VAR:
  #   value: "var2"
  #   secure: false
  # SOME_SEC_ENV_VAR:
  #   value: "var"
  #   secure: true

tls:
  enabled: false
  mountPath: "/etc/tls"
  secretName: ""
  secret:
    server.crt: ""
    server.key: ""
    ca.crt: ""

containerPort: 8000

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

rbac:
  create: false
  rules: []
  # RBAC rules for KUBE_PING
  #  - apiGroups:
  #      - ""
  #    resources:
  #      - pods
  #    verbs:
  #      - get
  #      - list

service:
  type: ClusterIP
  port: 80

livenessProbe:
  {}
  # httpGet:
  #   path: /
  #   port: http
readinessProbe:
  {}
  # httpGet:
  #   path: /
  #   port: http

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

rollingUpdate:
  maxUnavailable: 33%
  maxSurge: 33%

nodeSelector: {}

tolerations: []

affinity: {}

oauthProxy:
  enabled: false
  localUpstream: true
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v7.1.3

  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 128Mi

  config:
    http-address: "0.0.0.0:7999"
    email-domain: "*"
    provider: "oidc"
    client-id: ""
    client-secret: ""
    scope: openid
    oidc-issuer-url: ""
    cookie-secret: "not_secretenough"
    cookie-secure: true
    cookie-refresh: "3m"
    cookie-expire: "24h"
    pass-basic-auth: false
    pass-access-token: true
    set-xauthrequest: true
    skip-jwt-bearer-tokens: true
    oidc-email-claim: "sub"
    set-authorization-header: false
    pass-authorization-header: false
    insecure-oidc-allow-unverified-email: "true"
    skip-auth-regex: /public
    upstream: "http://127.0.0.1:8000"
    redirect-url: "<external url>/oauth2/callback"
