apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup-storage.fullname" . }}-config
  labels:
    app: {{ include "backup-storage.name" . }}
    chart: {{ include "backup-storage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  backup-file: |-
{{ .Values.backupConfig | indent 4 }}
{{- range .Values.config }}
  {{ .filename }}: |-
{{- with .contents }}
{{ . | indent 4 }}
{{- end }}
{{- with .yaml }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}