apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup-storage.fullname" . }}-config
  labels:
    app: {{ include "backup-storage.name" . }}
    chart: {{ include "backup-storage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  backup-file: |-
{{ .Values.backupConfig | indent 4 }}
