{{- if .Values.networkPolicy.enabled -}}
apiVersion: v1
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "backup-storage.fullname" . }}-networkpolicy
  labels:
    app: {{ include "backup-storage.name" . }}
    chart: {{ include "backup-storage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels: {{ include "backup-storage.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{  .Values.networkPolicy.backupServicePort }}
  podSelector:
    matchLabels:
      {{- with .Values.networkPolicy.selectorLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end -}}
